#!/bin/bash
BASE_DIR=.

BIN_DIR=$BASE_DIR/build/debug

TEST_DIR=$BASE_DIR/tests
INPUT_DIR=$TEST_DIR/input
OUTPUT_DIR=$TEST_DIR/output
EXPECT_DIR=$TEST_DIR/expect

rm -rf $OUTPUT_DIR
mkdir $OUTPUT_DIR

for FNAME in $(ls $INPUT_DIR) ; do
    echo $FNAME
    $BIN_DIR/bytecode_translation $INPUT_DIR/$FNAME 1 2 > $OUTPUT_DIR/$FNAME
done

diff -qr --exclude=".svn" $OUTPUT_DIR $EXPECT_DIR
